<?php

namespace Database\Seeders;

use App\Models\Pension;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PensionSeeder extends Seeder
{
    public function run(): void
    {
        $locations = array_keys(config('sites.location'));
        $pensions = [
            [
                'seq' => 1,
                'name' => '바다향기펜션',
                'owner' => '김철수',
                'tel' => '033-123-4567',
                'post' => '25000',
                'address_basic' => '강원도 강릉시 바다로 123',
                'address_local' => '강문동',
                'address_detail' => '101호',
                'address_jibun' => '강원도 강릉시 강문동 123-45',
                'lat' => '37.7749',
                'lng' => '128.9194',
                'location' => $locations[0] ?? '지역1',
                'reservation_key' => 'RES' . str_pad(1, 6, '0', STR_PAD_LEFT),
                'is_active' => true,
            ],
            [
                'seq' => 2,
                'name' => '산속휴양펜션',
                'owner' => '이영희',
                'tel' => '033-234-5678',
                'post' => '25100',
                'address_basic' => '강원도 평창군 산속로 456',
                'address_local' => '용평면',
                'address_detail' => '202호',
                'address_jibun' => '강원도 평창군 용평면 456-78',
                'lat' => '37.6329',
                'lng' => '128.6686',
                'location' => $locations[1] ?? '지역2',
                'reservation_key' => 'RES' . str_pad(2, 6, '0', STR_PAD_LEFT),
                'is_active' => true,
            ],
            [
                'seq' => 3,
                'name' => '솔향기펜션',
                'owner' => '박민수',
                'tel' => '033-345-6789',
                'post' => '25200',
                'address_basic' => '강원도 속초시 솔밭로 789',
                'address_local' => '조양동',
                'address_detail' => '1층',
                'address_jibun' => '강원도 속초시 조양동 789-12',
                'lat' => '38.2070',
                'lng' => '128.5918',
                'location' => $locations[2] ?? '지역3',
                'reservation_key' => 'RES' . str_pad(3, 6, '0', STR_PAD_LEFT),
                'is_active' => true,
            ],
            [
                'seq' => 4,
                'name' => '호수뷰펜션',
                'owner' => '최정희',
                'tel' => '033-456-7890',
                'post' => '25300',
                'address_basic' => '강원도 춘천시 호수로 321',
                'address_local' => '사북면',
                'address_detail' => '별관',
                'address_jibun' => '강원도 춘천시 사북면 321-56',
                'lat' => '37.8813',
                'lng' => '127.7298',
                'location' => $locations[3] ?? '지역4',
                'reservation_key' => 'RES' . str_pad(4, 6, '0', STR_PAD_LEFT),
                'is_active' => true,
            ],
            [
                'seq' => 5,
                'name' => '별빛정원펜션',
                'owner' => '정우성',
                'tel' => '033-567-8901',
                'post' => '25400',
                'address_basic' => '강원도 양양군 별빛로 654',
                'address_local' => '서면',
                'address_detail' => 'A동',
                'address_jibun' => '강원도 양양군 서면 654-89',
                'lat' => '38.0750',
                'lng' => '128.6190',
                'location' => $locations[4] ?? '지역5',
                'reservation_key' => 'RES' . str_pad(5, 6, '0', STR_PAD_LEFT),
                'is_active' => true,
            ],
            [
                'seq' => 6,
                'name' => '구름위펜션',
                'owner' => '강하늘',
                'tel' => '033-678-9012',
                'post' => '25500',
                'address_basic' => '강원도 정선군 구름로 987',
                'address_local' => '북평면',
                'address_detail' => 'B동 301호',
                'address_jibun' => '강원도 정선군 북평면 987-23',
                'lat' => '37.3807',
                'lng' => '128.6611',
                'location' => $locations[5] ?? '지역6',
                'reservation_key' => 'RES' . str_pad(6, 6, '0', STR_PAD_LEFT),
                'is_active' => true,
            ],
            [
                'seq' => 7,
                'name' => '단풍나무펜션',
                'owner' => '송중기',
                'tel' => '033-789-0123',
                'post' => '25600',
                'address_basic' => '강원도 인제군 단풍로 147',
                'address_local' => '기린면',
                'address_detail' => '2층',
                'address_jibun' => '강원도 인제군 기린면 147-36',
                'lat' => '38.0695',
                'lng' => '128.1708',
                'location' => $locations[6] ?? '지역7',
                'reservation_key' => 'RES' . str_pad(7, 6, '0', STR_PAD_LEFT),
                'is_active' => false, // 비활성 예시
            ],
            [
                'seq' => 8,
                'name' => '햇살가득펜션',
                'owner' => '유재석',
                'tel' => '033-890-1234',
                'post' => '25700',
                'address_basic' => '강원도 고성군 햇살로 258',
                'address_local' => '간성읍',
                'address_detail' => 'C동',
                'address_jibun' => '강원도 고성군 간성읍 258-47',
                'lat' => '38.3807',
                'lng' => '128.4677',
                'location' => $locations[7] ?? '지역8',
                'reservation_key' => 'RES' . str_pad(8, 6, '0', STR_PAD_LEFT),
                'is_active' => true,
            ],
        ];

        foreach ($pensions as $pension) {
            Pension::create([
                'seq' => $pension['seq'],
                'name' => $pension['name'],
                'owner' => $pension['owner'],
                'tel' => $pension['tel'],
                'post' => $pension['post'],
                'address_basic' => $pension['address_basic'],
                'address_local' => $pension['address_local'],
                'address_detail' => $pension['address_detail'],
                'address_jibun' => $pension['address_jibun'],
                'lat' => $pension['lat'],
                'lng' => $pension['lng'],
                'location' => $pension['location'],
                'reservation_key' => $pension['reservation_key'],
                'is_active' => $pension['is_active'],
            ]);
        }
    }
}
